import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Cloudify : Forget Password",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div
			className={`w-full h-full fixed z-50 left-0 top-0 bg-gradient-to-bl from-secondary-400 to-primary-400 backdrop-blur-lg flex justify-center items-center dark:from-black dark:to-black`}
		>
			{children}
		</div>
	);
}
